name: Translate ConnectIQStore texts
run-name: Translate ConnectIQStore texts by @${{ github.actor }}
on:
  # push:
  #  branches:
  #    - 'main'
  workflow_dispatch:
jobs:
  build:
    name: Translate ConnectIQStore texts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- name: read content
      #  id: content
      #  run: echo "content=$(cat ConnectIQStore/MeditateStoreDescription-en.txt)" >> "$GITHUB_OUTPUT"
      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.CHATGPT_TOKEN }}
      - name: translate to german
        run: /gpt-translate ConnectIQStore/MeditateStoreDescription-en.txt ConnectIQStore/MeditateStoreDescription-de.txt german
      - name: debug
        run: cat ConnectIQStore/MeditateStoreDescription-de.txt
