name: Translate ConnectIQStore texts
run-name: Translate ConnectIQStore texts by @${{ github.actor }}
on:
  # push:
  #  branches:
  #    - 'main'
  workflow_dispatch:
jobs:
  build:
    name: Translate ConnectIQStore texts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: read content
        id: content
        run: echo "content=$(< ConnectIQStore/MeditateStoreDescription-en.txt)" >> "$GITHUB_OUTPUT"
      - name: OpenAI ChatGPT Action
        id: de
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: "Translate the following description of a garmin app into german. don't change the format and consider the output must be suitable for a .txt file. no boilerplate.: ${{ steps.content.outputs.content }}"
          input: 'put whatever you want in here'
          model: 'gpt-4o'
          temperature: 1
          max_tokens: 200
      - name: write response to file
        run: echo "${{ steps.de.outputs.completion }}" > ConnectIQStore/MeditateStoreDescription-de.txt
      - name: debug
        run: ls -lah ConnectIQStore/ && cat ConnectIQStore/MeditateStoreDescription-de.txt
