name: Translate texts, guides, etc
run-name: Translate texts, guides, etc by @${{ github.actor }}
on:
  push:
    tags:
      - V*
      - v*
  workflow_dispatch:
jobs:
  translate_texts:
    name: Translate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cleanup release-translation branch
        run: |
          git push -d origin release-translation || echo "no remote branch to cleanup"
          git branch -d release-translation || echo "no local branch to cleanup"
      
      ################### UserGuide
      - name: read content
        id: store-content
        # needs encoding in base64 to be able to pass multiline 
        run: |
          echo "content=$(cat ./ConnectIQStore/MeditateStoreDescription-en.txt | base64 --wrap=0)" >> $GITHUB_OUTPUT
          echo "prompt=$(grep -v '[/|#]' ./.github/workflows/translate-content-store-prompt.txt | awk '{print}' ORS=' ')" >> $GITHUB_OUTPUT
          echo "model=$(grep -v '[/|#]' -m 1 ./.github/workflows/translate-content-model.txt)" >> $GITHUB_OUTPUT

      # german
      - name: OpenAI ChatGPT Action
        id: de
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: '${{ steps.store-content.outputs.prompt }} german'
          input: '${{ steps.store-content.outputs.content }}'
          model: '${{ steps.store-content.outputs.model }}'
      - name: write response to file
        run: |
          cat > ./ConnectIQStore/MeditateStoreDescription-de.txt << EOF
          ${{ steps.de.outputs.completion }}
      - name: cat
        run: cat ./ConnectIQStore/MeditateStoreDescription-de.txt
      
      # korean
      - name: OpenAI ChatGPT Action
        id: ko
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: '${{ steps.store-content.outputs.prompt }} korean'
          input: '${{ steps.store-content.outputs.content }}'
          model: '${{ steps.store-content.outputs.model }}'
      - name: write response to file
        run: |
            cat > ./ConnectIQStore/MeditateStoreDescription-ko.txt << EOF
            ${{ steps.ko.outputs.completion }}
      
      # portuguese
      - name: OpenAI ChatGPT Action
        id: pt
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: '${{ steps.store-content.outputs.prompt }} portuguese'
          input: '${{ steps.store-content.outputs.content }}'
          model: '${{ steps.store-content.outputs.model }}'
      - name: write response to file
        run: |
            cat > ./ConnectIQStore/MeditateStoreDescription-pt.txt << EOF
            ${{ steps.pt.outputs.completion }}

      # spanish
      - name: OpenAI ChatGPT Action
        id: es
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: '${{ steps.store-content.outputs.prompt }} spanish'
          input: '${{ steps.store-content.outputs.content }}'
          model: '${{ steps.store-content.outputs.model }}'
      - name: write response to file
        run: |
            cat > ./ConnectIQStore/MeditateStoreDescription-es.txt << EOF
            ${{ steps.es.outputs.completion }}
      
      ################### UserGuide
      - name: read content
        id: userguide-content
        # needs encoding in base64 to be able to pass multiline 
        run: |
          echo "content=$(cat ./UserGuide.md | base64 --wrap=0)" >> $GITHUB_OUTPUT
          echo "prompt=$(grep -v '[/|#]' ./.github/workflows/translate-content-userguide-prompt.txt | awk '{print}' ORS=' ')" >> $GITHUB_OUTPUT
          echo "model=$(grep -v '[/|#]' -m 1 ./.github/workflows/translate-content-model.txt)" >> $GITHUB_OUTPUT

      # german
      - name: OpenAI ChatGPT Action
        id: userguide-de
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: '${{ steps.userguide-content.outputs.prompt }} german'
          input: '${{ steps.userguide-content.outputs.content }}'
          model: '${{ steps.userguide-content.outputs.model }}'
      - name: write response to file
        run: |
            cat > ./UserGuide-de.md << EOF
            ${{ steps.userguide-de.outputs.completion }}
      
      # korean
      - name: OpenAI ChatGPT Action
        id: userguide-ko
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: '${{ steps.userguide-content.outputs.prompt }} korean'
          input: '${{ steps.userguide-content.outputs.content }}'
          model: '${{ steps.userguide-content.outputs.model }}'
      - name: write response to file
        run: |
            cat > ./UserGuide-ko.md << EOF
            ${{ steps.userguide-ko.outputs.completion }}
      
      # portuguese
      - name: OpenAI ChatGPT Action
        id: userguide-pt
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: '${{ steps.userguide-content.outputs.prompt }} portuguese'
          input: '${{ steps.userguide-content.outputs.content }}'
          model: '${{ steps.userguide-content.outputs.model }}'
      - name: write response to file
        run: |
            cat > ./UserGuide-pt.md << EOF
            ${{ steps.userguide-pt.outputs.completion }}

      # spanish
      - name: OpenAI ChatGPT Action
        id: userguide-es
        uses: cahaseler/openai-api@v1.0.0
        with:
          apiKey: ${{ secrets.CHATGPT_TOKEN }}
          prompt: '${{ steps.userguide-content.outputs.prompt }} spanish'
          input: '${{ steps.userguide-content.outputs.content }}'
          model: '${{ steps.userguide-content.outputs.model }}'
      - name: write response to file
        run: |
            cat > ./UserGuide-es.md << EOF
            ${{ steps.userguide-es.outputs.completion }}

      # create PR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release-translation
          commit-message: merge auto-generated translations

    
      # push
      - name: git add
        run: git add .
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: auto-generated translations
          branch: release-translation
          github_token: ${{ secrets.GITHUB_TOKEN }}
