name: Translate ConnectIQStore texts
run-name: Translate ConnectIQStore texts by @${{ github.actor }}
on:
  # push:
  #  branches:
  #    - 'main'
  workflow_dispatch:
jobs:
  build:
    name: Translate ConnectIQStore texts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- name: read content
      #  id: content
      #  run: echo "content=$(cat ConnectIQStore/MeditateStoreDescription-en.txt)" >> "$GITHUB_OUTPUT"
      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          # https://github.com/3ru/gpt-translate/blob/master/action.yml
          apikey: ${{ secrets.CHATGPT_TOKEN }}
          # space delimited strings
          inputFiles: "./ConnectIQStore/MeditateStoreDescription-en.txt"
          outputFiles: "./ConnectIQStore/MeditateStoreDescription-de.txt"
          languages: "german"
          prompt: "Translate the given text into {targetLanguage}. The output must be suitable for a txt file."
      - name: debug
        run: cat ConnectIQStore/MeditateStoreDescription-de.txt
