name: Translate ConnectIQStore texts
run-name: Translate ConnectIQStore texts by @${{ github.actor }}
on:
  # push:
  #  branches:
  #    - 'main'
  workflow_dispatch:
jobs:
  build:
    name: Translate ConnectIQStore texts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: read content
        id: content
        run: echo "content=$(cat ConnectIQStore/MeditateStoreDescription-en.txt)" >> "$GITHUB_OUTPUT"

      - name: translate to german with chatgpt
        id: de
        uses: BorislavStefanov31/chatgpt-action@v1.0.0
        with:
          openai_api_key: ${{ secrets.CHATGPT_TOKEN }}
          message: 'Translate the following description of a garmin app into german. keep the formating and keep the links in raw. just translate in raw without anyboilerplate: ${{ steps.content.outputs.content }}'
          temperature: 0.7
          model: 'gpt-4o'
      - name: update german file
        run: echo "${{ steps.de.outputs.response_message }}" > ConnectIQStore/MeditateStoreDescription-de.txt
      - name: debug
        run: cat ConnectIQStore/MeditateStoreDescription-de.txt
